#!/usr/bin/python

def reverseList(x):

	j = len(x);
	for i in xrange(len(x)):
		j -= 1

		if j <= i:
		
			x[i], x[j] = x[j], x[i] 


	return(x)


tmp1 = [];
tmp2 = [1];
tmp3 = [2]; 
tmp4 = [1, 3, 4, 5, 9];

print tmp4
result = reverseList(tmp4)
tmp4.reverse()
print tmp4 == result